# Generated by Django 4.2 on 2023-12-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_container_delete_customer_delete_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_middlename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_p_number',
            field=models.TextField(max_length=20),
        ),
    ]
