# Generated by Django 4.2 on 2023-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_employee_e_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('p_number', models.TextField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
